# Generated by Django 4.2.13 on 2024-07-11 17:37

from django.db import migrations, models
import toi.models


class Migration(migrations.Migration):

    dependencies = [
        ('toi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='batch_start_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course_status',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_status',
            field=models.CharField(blank=True, choices=[('enrolled', 'enrolled'), ('completed', 'completed'), ('ongoing', 'ongoing')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[toi.models.validate_mobile_number]),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='user_type',
            field=models.CharField(blank=True, choices=[('user', 'user'), ('admin', 'admin'), ('employee', 'employee')], max_length=10, null=True),
        ),
    ]
