# Generated by Django 4.2.13 on 2024-07-17 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toi', '0002_remove_student_batch_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='enrolled_student',
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='enrolled_course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='toi.course'),
        ),
    ]
