# Generated by Django 4.2.13 on 2024-07-28 06:19

from django.db import migrations, models
import toi.models


class Migration(migrations.Migration):

    dependencies = [
        ('toi', '0004_course_about_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[toi.models.validate_mobile_number]),
        ),
    ]
